-- notifications: in-app alerts generated by the nightly job (see
-- notifications.ts / scheduler.ts). is_read and is_resolved are separate on
-- purpose -- a person seeing an alert and the underlying condition actually
-- clearing are two different facts.
CREATE TABLE IF NOT EXISTS notifications (
    id SERIAL PRIMARY KEY,
    type TEXT NOT NULL,                          -- low_stock | stnk_expiry | aging_inventory
    severity TEXT NOT NULL,
    message TEXT NOT NULL,                        -- one-line human-readable text
    vehicle_id INTEGER REFERENCES vehicles(id),   -- set for stnk_expiry/aging_inventory, null for low_stock
    brand TEXT,                                   -- set for low_stock, null for the other two
    model_trim TEXT,                              -- set for low_stock, null for the other two
    is_read BOOLEAN NOT NULL DEFAULT false,
    is_resolved BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    resolved_at TIMESTAMPTZ(3),
    read_at TIMESTAMPTZ(3)
);

-- Lookups the job does every run: "is there already an active (unresolved)
-- notification of this type for this vehicle/group" and "which active
-- notifications of this type need re-checking for auto-resolve".
CREATE INDEX IF NOT EXISTS idx_notifications_type_resolved ON notifications (type, is_resolved);
CREATE INDEX IF NOT EXISTS idx_notifications_vehicle_id ON notifications (vehicle_id);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON notifications (is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications (created_at DESC);
