-- uploads: tracks each ingested Excel file
CREATE TABLE IF NOT EXISTS uploads (
    id SERIAL PRIMARY KEY,
    filename TEXT NOT NULL,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    rows_inserted INTEGER,      -- populated at insert time; NULL for uploads that predate this column
    rows_skipped INTEGER
);

-- vehicles: current snapshot, one row per physical unit
CREATE TABLE IF NOT EXISTS vehicles (
    id SERIAL PRIMARY KEY,
    license_plate TEXT,
    vin TEXT,
    engine_no TEXT,
    brand TEXT,
    model_trim TEXT,
    year INTEGER,
    transmission TEXT,
    color TEXT,
    odometer_km INTEGER,
    stnk_expiry_date DATE,
    purchase_date DATE,        -- date the unit was purchased/entered stock (derived from "Age" column on hardcoded formats, or mapped directly from a "Purchase Date" column via the template registry)
    handover_date DATE,        -- date the vehicle was handed over to the buyer; source files usually just label this column "HANDOVER"
    status TEXT,               -- available / booked / sold
    reserved_by TEXT,          -- populated when status = booked
    buyer_name TEXT,           -- populated when status = sold (see migration_add_buyer_name.sql)
    location TEXT,             -- best-effort parsed area/branch, nullable
    ownership TEXT,
    price_cash NUMERIC,
    price_credit NUMERIC,
    price_net NUMERIC,          -- distinct "Harga Net"/"Harga Jual (NETT)" price, never a synonym for cash or credit
    max_credit_discount TEXT,
    notes_raw TEXT,            -- original "Keterangan" string, kept as-is
    source TEXT,               -- trade-in / acquisition provenance
    upload_id INTEGER REFERENCES uploads(id),
    sheet_name TEXT,
    row_index INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now() -- millisecond precision: used as an optimistic-concurrency token, see migration_add_buyer_name.sql
);

CREATE INDEX IF NOT EXISTS idx_vehicles_brand ON vehicles (brand);
CREATE INDEX IF NOT EXISTS idx_vehicles_status ON vehicles (status);
CREATE INDEX IF NOT EXISTS idx_vehicles_location ON vehicles (location);
CREATE INDEX IF NOT EXISTS idx_vehicles_license_plate ON vehicles (license_plate);
CREATE INDEX IF NOT EXISTS idx_vehicles_purchase_date ON vehicles (purchase_date);

-- vehicle_transactions: history log per unit (purchase / sale / recon events)
CREATE TABLE IF NOT EXISTS vehicle_transactions (
    id SERIAL PRIMARY KEY,
    vehicle_id INTEGER REFERENCES vehicles(id),
    event_type TEXT,           -- purchase / sold / recon
    event_date DATE,
    purchase_price NUMERIC,
    recon_cost NUMERIC,
    selling_price_cash NUMERIC,
    selling_price_credit NUMERIC,
    gp_amount NUMERIC,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vehicle_transactions_vehicle_id ON vehicle_transactions (vehicle_id);

-- notifications: in-app alerts generated by the nightly job (see
-- notifications.ts / scheduler.ts, migration_add_notifications.sql).
-- is_read and is_resolved are separate on purpose -- a person seeing an
-- alert and the underlying condition actually clearing are two different
-- facts.
CREATE TABLE IF NOT EXISTS notifications (
    id SERIAL PRIMARY KEY,
    type TEXT NOT NULL,                          -- low_stock | stnk_expiry | aging_inventory
    severity TEXT NOT NULL,
    message TEXT NOT NULL,                        -- one-line human-readable text
    vehicle_id INTEGER REFERENCES vehicles(id),   -- set for stnk_expiry/aging_inventory, null for low_stock
    brand TEXT,                                   -- set for low_stock, null for the other two
    model_trim TEXT,                              -- set for low_stock, null for the other two
    is_read BOOLEAN NOT NULL DEFAULT false,
    is_resolved BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    resolved_at TIMESTAMPTZ(3),
    read_at TIMESTAMPTZ(3)
);

CREATE INDEX IF NOT EXISTS idx_notifications_type_resolved ON notifications (type, is_resolved);
CREATE INDEX IF NOT EXISTS idx_notifications_vehicle_id ON notifications (vehicle_id);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON notifications (is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications (created_at DESC);

-- import_templates: known header-row shapes and how to map their columns to
-- the vehicles table, so POST /api/upload can recognize a previously-seen
-- format without re-asking the AI. header_fingerprint is a hash of the
-- normalized header row (see templates.ts); column_mapping is a JSON object
-- of { headerRow, dataStartRow, columns: { <vehicle field>: <column letter> },
-- locationDefault?, statusDefault? }.
CREATE TABLE IF NOT EXISTS import_templates (
    id SERIAL PRIMARY KEY,
    header_fingerprint TEXT NOT NULL UNIQUE,
    sheet_label TEXT NOT NULL,
    column_mapping JSONB NOT NULL,
    times_used INTEGER NOT NULL DEFAULT 0,      -- incremented on every confirm-mapping call for this template
    times_corrected INTEGER NOT NULL DEFAULT 0, -- incremented when the submitted mapping differs from what was originally proposed (see migration_add_template_usage_tracking.sql)
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
