<script setup lang="ts">
import { ref } from "vue";
import AlertBox from "./AlertBox.vue";
import ResultsTable from "./ResultsTable.vue";
import { askQuestion } from "../composables/useApi";
import type { AskResult } from "../types";

const question = ref("");
const isLoading = ref(false);
const result = ref<AskResult | null>(null);
const errorMessage = ref<string | null>(null);
const sessionTotalTokens = ref(0);

async function ask() {
  const q = question.value.trim();
  if (!q) return;

  isLoading.value = true;
  errorMessage.value = null;
  result.value = null;

  try {
    const res = await askQuestion(q);
    result.value = res;
    if (res.usage) sessionTotalTokens.value += res.usage.total_tokens;
  } catch (err) {
    errorMessage.value = err instanceof Error ? err.message : String(err);
  } finally {
    isLoading.value = false;
  }
}
</script>

<template>
  <div>
    <h2 class="text-2xl font-semibold mb-1">Ask AI</h2>
    <p class="text-sm text-gray-500 mb-6">
      Ask a question about what's in stock. Each question makes exactly one AI call -- the
      answer itself is computed directly from the database, not generated by the model.
    </p>

    <form class="flex gap-2 mb-6" @submit.prevent="ask">
      <input
        v-model="question"
        type="text"
        placeholder='e.g. "How many Hondas are in stock?"'
        class="flex-1 rounded-md border border-gray-300 px-4 py-2.5 text-sm"
      />
      <button
        type="submit"
        class="rounded-md bg-blue-600 px-5 py-2.5 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50"
        :disabled="isLoading || !question.trim()"
      >
        {{ isLoading ? "Asking..." : "Ask" }}
      </button>
    </form>

    <AlertBox v-if="errorMessage" variant="error" class="mb-6">
      {{ errorMessage }}
    </AlertBox>

    <AlertBox v-if="result?.status === 'needs_clarification'" variant="warning" class="mb-6">
      <strong>Need a bit more detail:</strong> {{ result.message }}
    </AlertBox>

    <div v-if="result?.status === 'answered'" class="mb-6">
      <AlertBox variant="success" class="mb-3">
        {{ result.summary }}
      </AlertBox>

      <ResultsTable :rows="result.rows" class="mb-3" />

      <details class="text-xs text-gray-500">
        <summary class="cursor-pointer select-none">SQL used</summary>
        <pre class="mt-2 whitespace-pre-wrap rounded bg-gray-900 p-3 text-gray-100">{{ result.sql }}</pre>
      </details>
    </div>

    <div v-if="result?.usage" class="text-xs text-gray-500 border-t border-gray-200 pt-4 mt-4">
      This question: {{ result.usage.prompt_tokens }} prompt + {{ result.usage.completion_tokens }} completion
      = {{ result.usage.total_tokens }} tokens.
      <span v-if="sessionTotalTokens > 0"> Session total: {{ sessionTotalTokens }} tokens.</span>
    </div>
  </div>
</template>
